<?php
require_once 'includes/auth.php';
require_once 'includes/fuel_functions.php';

// Only admin and superadmin can access
if (!in_array($_SESSION['role'], ['admin', 'superadmin'])) {
    $_SESSION['error'] = 'Access denied. Admins only.';
    header('Location: index.php');
    exit;
}

// Get the fuel purchase ID
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
if (!$id) {
    $_SESSION['error'] = 'Invalid fuel purchase ID';
    header('Location: fuel_history.php');
    exit;
}

// Get the fuel purchase details
$purchase = getFuelPurchaseDetails($id);
if (!$purchase) {
    $_SESSION['error'] = 'Fuel purchase not found';
    header('Location: fuel_history.php');
    exit;
}

// Include the TCPDF library
require_once 'tcpdf/tcpdf.php';

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('WashHub');
$pdf->SetAuthor('WashHub');
$pdf->SetTitle('Fuel Purchase Report - ' . date('Y-m-d', strtotime($purchase['start_date'])));
$pdf->SetSubject('Fuel Purchase Report');
$pdf->SetKeywords('Fuel, Report, WashHub');

// Remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 10);

// Add logo and title
if (file_exists('../frontend/new logo.png')) {
    $pdf->Image('../frontend/new logo.png', 15, 10, 30, 0, '', '', '', false, 300, '', false, false, 0);
}
$pdf->SetY(15);
$pdf->SetFont('helvetica', 'B', 18);
$pdf->Cell(0, 10, 'Fuel Purchase Report', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(0, 5, 'Generated on: ' . date('F j, Y h:i A'), 0, 1, 'C');
$pdf->Ln(10);

// Add fuel details
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 8, 'Fuel Purchase Details', 0, 1, 'L');
$pdf->SetFont('helvetica', '', 10);

$html = <<<EOD
<table border="0.5" cellpadding="4" cellspacing="0">
    <tr style="background-color:#f2f2f2;">
        <th width="30%"><b>Field</b></th>
        <th width="70%"><b>Value</b></th>
    </tr>
    <tr>
        <td>Purchase Date</td>
        <td>{$purchase['start_date']}</td>
    </tr>
    <tr>
        <td>Status</td>
        <td>{$purchase['status']}</td>
    </tr>
    <tr>
        <td>Amount (GHS)</td>
        <td>GHS {$purchase['amount_cedis']}</td>
    </tr>
    <tr>
        <td>Liters</td>
        <td>{$purchase['liters']} L</td>
    </tr>
    <tr>
        <td>Price per Liter</td>
        <td>GHS {$purchase['price_per_liter']}</td>
    </tr>
</table>
EOD;

$pdf->writeHTML($html, true, false, true, false, '');

// Add wash statistics if available
if ($purchase['total_washes'] > 0) {
    $pdf->Ln(10);
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(0, 8, 'Wash Statistics', 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 10);
    
    $html = <<<EOD
    <table border="0.5" cellpadding="4" cellspacing="0">
        <tr style="background-color:#f2f2f2;">
            <th width="50%"><b>Metric</b></th>
            <th width="50%"><b>Value</b></th>
        </tr>
        <tr>
            <td>Total Washes</td>
            <td>{$purchase['total_washes']}</td>
        </tr>
        <tr>
            <td>Car Washes</td>
            <td>{$purchase['total_cars']}</td>
        </tr>
        <tr>
            <td>Motor Washes</td>
            <td>{$purchase['total_motors']}</td>
        </tr>
        <tr>
            <td>Cost per Wash</td>
            <td>GHS {$purchase['cost_per_wash']}</td>
        </tr>
    </table>
EOD;
    
    $pdf->writeHTML($html, true, false, true, false, '');
}

// Add footer
$pdf->SetY(-15);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 10, 'Generated by WashHub - ' . date('Y-m-d H:i:s'), 0, 0, 'C');

// Close and output PDF document
$pdf->Output('fuel_report_' . $id . '.pdf', 'D');
?>

